services:
  - name: geth-backend
    type: web
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run server"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8000

  - name: geth-frontend
    type: static
    buildCommand: "npm run build"
    publishDir: src/build
